### ISSUE TITLE
fnr-pg is missing package.json

### ISSUE THREAD

**Issue by theNerd247** [unfoldingWord/findr#16]
@abelpz  The `package.json` is missing and is preventing `typedoc` from working. Was not adding a `package.json` on purpose? If not is there any reason against adding one?

**Comment by abelpz** [comment]
No reason it just wasn't needed as fnr-pg is not a package but an app, so nx doesn't generate one. But you can add one if needed.

**Comment by theNerd247** [comment]
Closing as this is isn't an issue currently.
