### ISSUE TITLE
Build Pipeline Is Failing

### ISSUE THREAD

**Issue by theNerd247** [unfoldingWord/findr#6]
The current build pipeline for #5 is failing and I'm sure other PRs will run into the same issue as the only file that changed is the `README.md` file.

**Comment by abelpz** [comment]
@theNerd247 this is actually a documentation error, it fails because that target does not exist, nor ir should, and fnr-mui is not an app. The example should be `pnpm nx preview fnr-pg`

**Comment by abelpz** [comment]
> The current build pipeline for #5 is failing and I'm sure other PRs will run into the same issue as the only file that changed is the `README.md` file.

What's build pipeline is failing? Not sure I am understanding this issue.

**Comment by theNerd247** [comment]
See the build pipeline for #5. There are multiple pipelines that are failing to build

<img width="842" alt="Screenshot 2023-07-17 at 12 48 19 PM" src="https://github.com/unfoldingWord/findr/assets/910991/6a04495c-f44e-4f52-9c03-706ef1f20133">

**Comment by abelpz** [comment]
> See the build pipeline for #5. There are multiple pipelines that are failing to build
> 
> <img alt="Screenshot 2023-07-17 at 12 48 19 PM" width="842" src="https://user-images.githubusercontent.com/910991/254010360-6a04495c-f44e-4f52-9c03-706ef1f20133.png">

I am not even sure what those are about, those are set automatically by Nx on installation, but haven't been a problem so far, I have been able to build, test, and publish any library or app without anyproblems.

**Comment by theNerd247** [comment]
Ah, okie dokie! I didn't have any context for these issues either. I'll investigate what's going on further and create a PR if necessary

**Comment by theNerd247** [comment]
Hey @abelpz  it looks like the nx system pre-configured the github repo to use some default CI stuff. I've pushed a fix that was preventing most of the other jobs from failing however the main process is still failing. However, this failing job has the following log: 

```
Run ${GITHUB_WORKSPACE//\\//}/.github/workflows/run-commands-in-parallel.sh '["NX_CLOUD_DISTRIBUTED_EXECUTION=false pnpm exec nx-cloud record -- pnpm exec nx format:check","pnpm exec nx affected --target=lint --parallel=3","pnpm exec nx affected --target=test --parallel=3 --ci --code-coverage","pnpm exec nx affected --target=build --parallel=3"]'

 >  NX   No explicit --base argument provided, but found environment variable NX_BASE so using its value as the affected base: 131df9c8f6e8e4cfe3313d40ad01e9cec56ad9d1


 >  NX   No explicit --head argument provided, but found environment variable NX_HEAD so using its value as the affected head: d91eb628a7c78f236ff577d5a36f3b5af234e6dc



 >  NX   No explicit --base argument provided, but found environment variable NX_BASE so using its value as the affected base: 131df9c8f6e8e4cfe3313d40ad01e9cec56ad9d1


 >  NX   No explicit --head argument provided, but found environment variable NX_HEAD so using its value as the affected head: d91eb628a7c78f236ff577d5a36f3b5af234e6dc

 >  NX   No explicit --base argument provided, but found environment variable NX_BASE so using its value as the affected base: 131df9c8f6e8e4cfe3313d40ad01e9cec56ad9d1


 >  NX   No explicit --head argument provided, but found environment variable NX_HEAD so using its value as the affected head: d91eb628a7c78f236ff577d5a36f3b5af234e6dc

README.md
package.json

> nx run fnr-docs:build 
[INFO] [en] Creating an optimized production build...
[info] [webpackbar] Compiling Client
[info] [webpackbar] Compiling Server
[success] [webpackbar] Client: Compiled successfully in 35.44s
[success] [webpackbar] Server: Compiled successfully in 38.12s
[SUCCESS] Generated static files in "dist/packages/fnr-docs".
[INFO] Use `npm run serve` command to test your build locally.

 

pnpm-lock.yaml

 


 >  NX   Nx Cloud: Successfully recorded command output

   You can view or share your output by visiting https://cloud.nx.app/runs/3Q7TGfguoo


 >  NX   Successfully completed running the command.

   See run details at https://cloud.nx.app/runs/do9vJEDwkT

Error: Process completed with exit code 1.
```

The last part is rather confusing...as no errors are indicated in why the build fails.

**Comment by abelpz** [comment]
The report by Nx Cloud says this is the command that is failing: `pnpm exec nx format:check` However it works by running it locally

**Comment by abelpz** [comment]
@theNerd247 are you able now? I've just made it public.

**Comment by theNerd247** [comment]
yes, thank you!

**Comment by theNerd247** [comment]
Here are the issues that I've discovered so far and are attempting to fix in #5. 

 1. the pre-build phase was having errors because the version of `pnpm` chosen did not match the version of `pnpm` that the project expects to use
 2. the `format:check` command is still broken.
 3. the `workspace-lint` command is deprecated but still included in the generated `ci.yml`. 
 
After fixing these issues the linter is now throwing multiple errors in the source code. I propose we remove the CI for this PR (since we're only updating the README) and create a separate PR for making the appropriate fixes for the CI around this repo - that and I believe we need a separate issue to discuss the goals the CI should have for this repo.

**Comment by abelpz** [comment]
@theNerd247 sure, we can go ahead with it as you proposed.

**Comment by theNerd247** [comment]
in light of #5 being merged I'm closing this since it removes the templated CI process. #31 was merged today and introduces a new CI process that we can build upon
